# Docker Compose setup for development and production

version: '3.8'

services:
  # AI Product Search API
  search-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./output:/app/output:ro  # Mount pre-built indexes
      - ./data:/app/data:ro      # Mount category data
      - ./.env:/app/.env:ro      # Mount environment variables
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis cache for future enhancements
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

# volumes:
#   redis_data:
